# This is a basic workflow to help you get started with Actions

name: Deploy CUCore

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]
    paths: 
      - 'solutions/CUCore/**'
  release:
    types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Pack solution
        uses: microsoft/powerplatform-actions/pack-solution@v0.1.7
        with:
          solution-folder: 'solutions/CUCore/content'
          solution-file: out/CI/solutions/CUCore.zip
          solution-type: Unmanaged
      
      - name: Upload the ready to ship solution to GH artifact store
        uses: actions/upload-artifact@v2
        with:
          name: managedSolutions
          path: out/CI/solutions/CUCore.zip
