
name: Manual or API export and commit CUCore

on:
   repository_dispatch: 
    types: [ export_cucore]
   workflow_dispatch:

# Define solution name in one place.
env: 
   SOLUTION_NAME: CUCore
   CRM_URL: https://orgdfc3d319.crm.dynamics.com/

jobs:

  build:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v2

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0.1.7
        with:
          environment-url: ${{ env.CRM_URL }}
          user-name: ${{ secrets.USERNAME }}
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: out/exported/${{ env.SOLUTION_NAME }}.zip

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0.1.7
        with:
          solution-file: out/exported/${{ env.SOLUTION_NAME }}.zip
          solution-folder: out/solutions/${{ env.SOLUTION_NAME }}
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0.1.7
        with:
          solution-folder: out/solutions/${{ env.SOLUTION_NAME }}
          solution-target-folder: solutions/${{ env.SOLUTION_NAME }}/content
          repo-token: ${{ secrets.GITHUBTOKEN }}
          allow-empty-commit: true
